version: '3.7'

services:
  bot-core-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/app/src
      - ./nodemon.json:/home/app/nodemon.json
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev